# Generated by Django 5.0.6 on 2024-09-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0002_alter_store_subscribe_alter_user_email_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='StoreStaff',
        ),
    ]
