# Generated by Django 5.0.6 on 2024-09-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0005_user_description_user_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
