# Generated by Django 5.0.6 on 2024-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0006_rename_first_name_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='managerschedule',
            index=models.Index(fields=['manager', 'store', 'date'], name='booker_mana_manager_4d3386_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name', 'address'], name='booker_stor_name_548140_idx'),
        ),
        migrations.AddIndex(
            model_name='therapistschedule',
            index=models.Index(fields=['therapist', 'store', 'date'], name='booker_ther_therapi_04c4f6_idx'),
        ),
    ]
