# Generated by Django 5.0.6 on 2024-09-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0007_otp_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
    ]
