# Generated by Django 5.0.6 on 2024-09-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0008_therapistschedule_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistschedule',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
