# Generated by Django 5.0.6 on 2024-09-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0010_therapistschedule_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistschedule',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='therapistschedule',
            name='customer_name',
            field=models.CharField(default='Unknown Customer', max_length=255),
        ),
        migrations.AddField(
            model_name='therapistschedule',
            name='customer_phone',
            field=models.CharField(default='Unknown Phone', max_length=15),
        ),
    ]
