# Generated by Django 5.0.6 on 2024-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0011_therapistschedule_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistschedule',
            name='customer_confirmation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
