# Generated by Django 5.0.6 on 2024-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0012_therapistschedule_customer_confirmation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistschedule',
            name='previous_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistschedule',
            name='previous_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
