# Generated by Django 5.0.6 on 2024-10-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booker', '0013_therapistschedule_previous_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=25),
        ),
    ]
